plugins:
  - jekyll-remote-theme
title: LandonW
tagline: Songyue Wang's Homepage
google_analytics: 
show_downloads: true
cover: /melon.jpeg
remote_theme: zivong/jekyll-theme-hydure
class: wide
author:
  name: LandonWong
  url: https://github.com/LandonWong/
  
social:
  name: LandonWong
  links:
    - https://github.com/LandonWong/

lang: en_us
